{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 1, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 0}, "tests": {"0": {"status": "SKIP", "message": "('C:\\\\disk\\\\PyRestAPI\\\\APIAUtomation\\\\testCases\\\\Test_001.py', 11, 'Skipped: unconditional skip')\n", "test_name": "test001_url", "rerun": "0"}}, "suite_name": "testCases/Test_001.py"}, "1": {"suite_name": "testCases/Test_002.py", "tests": {"0": {"status": "FAIL", "message": "   socket.gaierror: [Errno 11001] getaddrinfo failed\n       urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x000001F5B1A14EC0>: Failed to resolve 'simple-books-api.glitch.me' ([Errno 11001] getaddrinfo failed)\n       urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='simple-books-api.glitch.me', port=443): Max retries exceeded with url: /orders (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x000001F5B1A14EC0>: Failed to resolve 'simple-books-api.glitch.me' ([Errno 11001] getaddrinfo failed)\"))\n       requests.exceptions.ConnectionError: HTTPSConnectionPool(host='simple-books-api.glitch.me', port=443): Max retries exceeded with url: /orders (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x000001F5B1A14EC0>: Failed to resolve 'simple-books-api.glitch.me' ([Errno 11001] getaddrinfo failed)\"))\n", "test_name": "test_002_Post", "rerun": "0"}, "1": {"status": "FAIL", "message": "   socket.gaierror: [Errno 11001] getaddrinfo failed\n       urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x000001F5B19FF750>: Failed to resolve 'simple-books-api.glitch.me' ([Errno 11001] getaddrinfo failed)\n       urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='simple-books-api.glitch.me', port=443): Max retries exceeded with url: /orders/ (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x000001F5B19FF750>: Failed to resolve 'simple-books-api.glitch.me' ([Errno 11001] getaddrinfo failed)\"))\n       requests.exceptions.ConnectionError: HTTPSConnectionPool(host='simple-books-api.glitch.me', port=443): Max retries exceeded with url: /orders/ (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x000001F5B19FF750>: Failed to resolve 'simple-books-api.glitch.me' ([Errno 11001] getaddrinfo failed)\"))\n", "test_name": "test_002_GetOrders", "rerun": "0"}, "2": {"status": "FAIL", "message": "   socket.gaierror: [Errno 11001] getaddrinfo failed\n       urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x000001F5B1F30550>: Failed to resolve 'simple-books-api.glitch.me' ([Errno 11001] getaddrinfo failed)\n       urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='simple-books-api.glitch.me', port=443): Max retries exceeded with url: /orders/ (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x000001F5B1F30550>: Failed to resolve 'simple-books-api.glitch.me' ([Errno 11001] getaddrinfo failed)\"))\n       requests.exceptions.ConnectionError: HTTPSConnectionPool(host='simple-books-api.glitch.me', port=443): Max retries exceeded with url: /orders/ (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x000001F5B1F30550>: Failed to resolve 'simple-books-api.glitch.me' ([Errno 11001] getaddrinfo failed)\"))\n", "test_name": "test_002_Patch", "rerun": "0"}, "3": {"status": "FAIL", "message": "   socket.gaierror: [Errno 11001] getaddrinfo failed\n       urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x000001F5B19FFC50>: Failed to resolve 'simple-books-api.glitch.me' ([Errno 11001] getaddrinfo failed)\n       urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='simple-books-api.glitch.me', port=443): Max retries exceeded with url: /orders/ (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x000001F5B19FFC50>: Failed to resolve 'simple-books-api.glitch.me' ([Errno 11001] getaddrinfo failed)\"))\n       requests.exceptions.ConnectionError: HTTPSConnectionPool(host='simple-books-api.glitch.me', port=443): Max retries exceeded with url: /orders/ (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x000001F5B19FFC50>: Failed to resolve 'simple-books-api.glitch.me' ([Errno 11001] getaddrinfo failed)\"))\n", "test_name": "test_002_GetOrders_2", "rerun": "0"}, "4": {"status": "FAIL", "message": "   socket.gaierror: [Errno 11001] getaddrinfo failed\n       urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x000001F5B19FF610>: Failed to resolve 'simple-books-api.glitch.me' ([Errno 11001] getaddrinfo failed)\n       urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='simple-books-api.glitch.me', port=443): Max retries exceeded with url: /orders/ (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x000001F5B19FF610>: Failed to resolve 'simple-books-api.glitch.me' ([Errno 11001] getaddrinfo failed)\"))\n       requests.exceptions.ConnectionError: HTTPSConnectionPool(host='simple-books-api.glitch.me', port=443): Max retries exceeded with url: /orders/ (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x000001F5B19FF610>: Failed to resolve 'simple-books-api.glitch.me' ([Errno 11001] getaddrinfo failed)\"))\n", "test_name": "test_002_DeletOrders", "rerun": "0"}}, "status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 5, "total_error": 0}}}}, "date": "January 01, 2025", "start_time": 1735711481.6947432, "total_suite": 2, "status": "FAIL", "status_list": {"pass": "0", "fail": "5", "skip": "1", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "6"}